### ISSUE TITLE
Ancient EAPI?

### ISSUE THREAD

**Issue by Thelorik** [fepitre/qubes-gentoo#13] opened 2023-04-05 02:05 UTC
Most recent EAPI is 8; attempting to sync with a recent world fails with an error of being incompatible with EAPI 7, but the config directory indicates EAPI 5? Is this delay intentional?

**Comment by lubellier** [comment] 2023-08-30 18:13
In Qubes-OS 4.1, since yesterday, my daily update reports the problem as an error:
```
These are the packages that would be merged, in reverse order:

Calculating dependencies   ERROR: app-emulation/qubes-gui-common-4.1.1::qubes failed (depend phase):  eutils: EAPI 7 not supported

 Call stack:
                     ebuild.sh, line 628:  Called source '/var/db/repos/qubes/app-emulation/qubes-gui-common/qubes-gui-common-4.1.1.ebuild'
  qubes-gui-common-4.1.1.ebuild, line   5:  Called inherit 'git-r3' 'eutils' 'multilib' 'qubes'
                    ebuild.sh, line 308:  Called __qa_source '/var/db/repos/gentoo/eclass/eutils.eclass'
                    ebuild.sh, line 123:  Called source '/var/db/repos/gentoo/eclass/eutils.eclass'
                 eutils.eclass, line  18:  Called die
The specific snippet of code:
     *) die "${ECLASS}: EAPI ${EAPI:-0} not supported" ;;
```
in fact all the ebuilds include the `EAPI=7` definition.

The (basic?) solution seems to replace all `EAPI=7` by `EAPI=8` in all `*.ebuild.0` in the git repository.

**Comment by lubellier** [comment] 2023-08-30 19:13
EAPI 7 [is not deprecated](https://wiki.gentoo.org/wiki/Project:Package_Manager_Specification) and my above basic solution doesn't work.
The previous EAPI change (from 6 to 7) commit : 7cb655c242e6581f10a025799f4fbfdf226e505d .

**Comment by ctr49** [comment] 2023-09-03 09:27
I'm also facing this issue and am also confused as EAPI7 should still be supported (couldn't find a Gentoo news release saying it isn't anymore).

But maybe a new issue should be opened as this has nothing to do with the original report (as this is a new issue since late August).

**Comment by ctr49** [comment] 2023-09-03 09:34
I found the root cause: The qubes ebuilds use the `eutils` class, but [eutils dropped EAPI7 support recently](https://gitweb.gentoo.org/repo/gentoo.git/commit/eclass/eutils.eclass?id=39c5ef0fe227a4781d1b2ea79ac6f336ec64f879).

So the solution would be to remove eutils from all qubes ebuilds and replace eutils functionality (if there are any left) with native functions.

**Comment by fepitre** [comment] 2023-11-20 08:46
It should be fixed now.

**Closed by fepitre** 2023-11-20 08:46 UTC
